function [verdict]=boxCollide(horzc1,vertc1,width1,height1,...
                              horzc2,vertc2,width2,height2)
verdict = (abs(horzc1-horzc2)*2 <= (width1+width2)) &&...
          (abs(vertc1-vertc2)*2 <= (height1+height2));
end